live_config_reload = true

[env]
	TERM = "xterm-256color"

[window]
	startup_mode = "Fullscreen"

[font]
	size = 12.0

[mouse]
	hide_when_typing = true

[shell]
	program = "/bin/zsh"
	args    = ["--login"]
